version: '3'
services:
  angie:
    image: docker.angie.software/angie:1.7.0-ubuntu
    container_name: angie_server
    ports:
      - "80:80"    # Проброс порта 80 для HTTP
      - "443:443"  # Проброс порта 443 для HTTPS
    volumes:
      - ./config/angie.conf:/etc/angie/angie.conf:ro  # Монтирование конфигурации из хостовой директории
      - ./html:/usr/share/nginx/html:ro  # Веб-директория для сайта
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
